apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: restful-web-services-argocd-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jesusBB/restful-web-services_config.git
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: restful-web-services
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true #this will delete the service if the service.yaml file gets deleted