apiVersion: v1
kind: Service
metadata:
  name: restful-web-services-service
spec:
  selector:
    app: restful-web-services
  ports:
  - port: 8089
    protocol: TCP
    targetPort: 8080
  #  nodePort: 31111
  type: NodePort